# upstream spring_backend {
#     server travery-app:8080;
# }

# server {
#     listen 80;
#     server_name _;

#     # Block ALL external access to Actuator, but allow Nginx internal healthcheck
#     # Alloy scrapes Spring Boot internally via Docker DNS
#     location /actuator/ {
#         allow 127.0.0.1;
#         deny all;
#         proxy_pass http://spring_backend;
#     }

#     # Main application traffic
#     location / {
#         proxy_pass http://spring_backend;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;

#         proxy_connect_timeout 60s;
#         proxy_send_timeout 60s;
#         proxy_read_timeout 60s;
#     }
# }

upstream spring_backend {
    server travery-app:8080;
}

# Chuyển hướng mọi request HTTP (port 80) sang HTTPS (port 443), ngoại trừ healthcheck
server {
    listen 80 default_server;
    server_name _;

    # Cho phép Nginx Healthcheck (chạy bên trong Docker) gọi thẳng HTTP mà không bị chuyển hướng
    location /actuator/health {
        proxy_pass http://spring_backend;
    }

    # Các request HTTP khác sẽ bị bẻ lái sang HTTPS
    location / {
        return 301 https://travery.io.vn$request_uri;
    }
}

# Cấu hình giao thức HTTPS chính
server {
    listen 443 ssl;
    server_name travery.io.vn;

    # Trỏ tới chứng chỉ SSL mà Certbot vừa tạo
    ssl_certificate /etc/letsencrypt/live/travery.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/travery.io.vn/privkey.pem;

    location /actuator/ {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://spring_backend;
    }

    location / {
        proxy_pass http://spring_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

