server:
  port: ${DEV_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate # Không dùng none, ép buộc entity phải khớp với flyway
    show-sql: false # Sử dụng log bên dưới nên tắt ở đây
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  threads:
    virtual:
      enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 30
    connect-retries-interval: 5

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

  otp:
    length: ${OTP_LENGTH:6}
    ttl-minutes: ${OTP_TTL_MINUTES}
    max-attempts: ${MAX_ATTEMPTS:3}
    resend-cooldown-seconds: ${RESEND_COOLDOWN_SECONDS:60}
    reset-max-per-hour: ${RESET_MAX_PER_HOUR}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    default-avatar-url: ${CLOUDINARY_DEFAULT_AVATAR_URL}
    allowed-image-types: ${CLOUDINARY_ALLOWED_IMAGE_TYPES}
    allowed-video-types: ${CLOUDINARY_ALLOWED_VIDEO_TYPES}
    avatar-size: ${CLOUDINARY_AVATAR_SIZE}
    thumbnail-size: ${CLOUDINARY_THUMBNAIL_SIZE}
    post-image-width: ${CLOUDINARY_POST_IMAGE_WIDTH}
    post-image-height: ${CLOUDINARY_POST_IMAGE_HEIGHT}

  post:
    limit-upload-images: ${POST_LIMIT_UPLOAD_IMAGES}
    limit-upload-videos: ${POST_LIMIT_UPLOAD_VIDEOS}

  thread:
    core-thread-pool-size: ${CORE_THREAD_POOL_SIZE}
    max-thread-pool-size: ${MAX_THREAD_POOL_SIZE}
    thread-queue-capacity: ${THREAD_QUEUE_CAPACITY}

  scalar:
    path: ${SCALAR_PATH:/docs}
    url: ${SCALAR_URL:/v3/api-docs}
    enabled: ${SCALAR_ENABLED:true}

logging:
  level:
    root: INFO
    com.travery.traverybackend: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG # Thêm cái này để xem query đẹp hơn

