upstream spring_backend {
    server travery-app:8080;
}

server {
    listen 80;
    server_name _;

    # Block ALL external access to Actuator
    # Alloy scrapes Spring Boot internally via Docker DNS
    location /actuator/ {
        deny all;
        return 403;
    }

    # Main application traffic
    location / {
        proxy_pass http://spring_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
