// Discovery: Automatically find Docker containers
discovery.docker "docker_containers" {
  host = "unix:///var/run/docker.sock"
}

// Process 1: Relabel Docker metadata into clean Loki labels
discovery.relabel "docker_relabel" {
  targets = discovery.docker.docker_containers.targets

  rule {
    action = "replace"
    source_labels = ["__meta_docker_container_name"]
    target_label = "container_name"
  }
  rule {
    action = "replace"
    source_labels = ["__meta_docker_container_label_com_docker_compose_service"]
    target_label = "service"
  }
  rule {
    action = "replace"
    source_labels = ["__meta_docker_container_id"]
    target_label = "container_id"
  }
}

// Log collection (tailing Docker logs)
loki.source.docker "docker_logs" {
  host = "unix:///var/run/docker.sock"
  targets = discovery.relabel.docker_relabel.output
  forward_to = [loki.process.docker_logs_pipeline.receiver]
}

// Log pipeline processing
loki.process "docker_logs_pipeline" {
  stage.json {
    expressions = {
      output = "log",
      stream = "stream",
    }
  }
  stage.labels {
    values = {
      stream = "stream",
    }
  }
  forward_to = [loki.write.loki_push.receiver]
}

// Log output
loki.write "loki_push" {
  endpoint {
    url = "http://" + sys.env("LOKI_HOST") + ":3100/loki/api/v1/push"
  }
}

// Metric collection - Host metric
prometheus.exporter.unix "unix_metrics" {
  disable_collectors = [
    "selinux", 
    "schedstat",
  ]
}

// Scrape Host metrics
prometheus.scrape "unix_scrape" {
  targets = prometheus.exporter.unix.unix_metrics.targets
  job_name = "node-exporter"
  scrape_interval = "30s"
  forward_to = [prometheus.relabel.unix_relabel.receiver]
}

// Fix weird Docker container IDs in Host metrics
prometheus.relabel "unix_relabel" {
  rule {
    action = "replace"
    target_label = "job"
    replacement = "node-exporter"
  }
  rule {
    action = "replace"
    target_label = "instance"
    replacement = "travery-server-1"
  }
  rule {
    action = "replace"
    target_label = "nodename"
    replacement = "travery-server-1"
  }
  forward_to = [prometheus.relabel.add_server_label.receiver]
}

// Metric collection - Prometheus Remote endpoint Scraping
prometheus.scrape "spring_boot" {
  targets = [
    {
      __address__ = "travery-app:8080",
      __scheme__ = "http", 
      __metrics_path__ = "/actuator/prometheus",
      job = "spring-boot", 
      instance = "travery-backend",
    },
  ]
  scrape_interval = "30s"
  scrape_timeout = "10s"
  forward_to = [prometheus.relabel.add_server_label.receiver]
}

// Metric processing
prometheus.relabel "add_server_label" {
  rule {
    target_label = "server"
    replacement = "server1"
  }
  forward_to = [prometheus.remote_write.prometheus_push.receiver]
}

// Metric output 
prometheus.remote_write "prometheus_push" {
  endpoint {
    url = "http://" + sys.env("PROMETHEUS_HOST") + ":9090/api/v1/write"
  }
}

// Export Metrics from both source for local debuggin
prometheus.exporter.unix "unix_for_export" {
  disable_collectors = [
    "selinux", 
    "schedstat",
  ]
}

prometheus.scrape "unix_scrape_local" {
  targets = prometheus.exporter.unix.unix_for_export.targets
  scrape_interval = "30s"
  forward_to = [prometheus.remote_write.localhost.receiver]
}

prometheus.scrape "spring_boot_for_export" {
  targets = [
    {
      __address__ = "travery-app:8080",
      __scheme__ = "http", 
      __metrics_path__ = "/actuator/prometheus", 
      job = "spring-boot", 
      instance = "travery-backend",
    },
  ]
  scrape_interval = "30s"
  scrape_timeout = "10s"
  forward_to = [prometheus.remote_write.localhost.receiver]
}

prometheus.remote_write "localhost" {
  endpoint {
    url = "http://localhost:9090/api/v1/write"
  }
}
